// Generates src/styles/theme.css and src/tokens.ts from tokens/tokens.json and tokens/extend.json.
// After changing either file, run `pnpm --filter @dailyx/ui tokens` and commit the outputs.
import { readFileSync, writeFileSync } from 'node:fs';

interface Token {
  name: string;
  value: string;
}

interface TypeStyle {
  name: string;
  family?: string;
  fontSize: string;
  lineHeight: string;
  fontWeight: number;
  letterSpacing?: string;
}

export interface TokenSource {
  color: { tokens: Token[] };
  type: {
    families: Record<string, string>;
    groups: { family: string; styles: TypeStyle[] }[];
  };
  spacing: { tokens: Token[] };
  radius: { tokens: Token[] };
  shadow: { tokens: Token[] };
  duration: { tokens: Token[] };
  easing: { tokens: Token[] };
}

type ExtendGroup =
  | 'color'
  | 'spacing'
  | 'radius'
  | 'fontSize'
  | 'leading'
  | 'tracking'
  | 'shadow'
  | 'dropShadow'
  | 'duration'
  | 'breakpoint'
  | 'gridCols';

// bundle.css values that tokens.json lacks (ADR 0002). Names are used verbatim.
export type ExtendSource = Record<ExtendGroup, { tokens: Token[] }>;

// Tailwind namespaces cleared so that only tokens compile. Breakpoints, containers, font
// weights, leading and tracking keep Tailwind's defaults.
const RESET = [
  'color',
  'spacing',
  'radius',
  'shadow',
  'inset-shadow',
  'drop-shadow',
  'text-shadow',
  'font',
  'text',
  'ease',
];

const HEADER =
  'Generated by packages/ui/scripts/build-tokens.ts from packages/ui/tokens/tokens.json and extend.json. Do not edit.';

const strip = (name: string, prefix: string) =>
  name.startsWith(prefix) ? name.slice(prefix.length) : name;

const referenceOf = (value: string) => /^\{(.+)\}$/.exec(value)?.[1];

// A reference stays an alias in CSS: {up} → var(--color-up).
const alias = (value: string) => {
  const ref = referenceOf(value);
  return ref === undefined ? value : `var(--color-${ref})`;
};

const vars = (namespace: string, record: Record<string, string>) =>
  Object.entries(record).map(([key, value]) => `--${namespace}-${key}: ${value};`);

// An extension may add names, never redefine one; a silent override would change a token.
const merge = (base: Record<string, string>, extra: Record<string, string>, group: string) => {
  for (const key of Object.keys(extra)) {
    if (key in base)
      throw new Error(`extend.json: ${group} "${key}" already exists in tokens.json`);
  }
  return { ...base, ...extra };
};

export function buildTokens(
  source: TokenSource,
  extend: ExtendSource,
): { css: string; ts: string } {
  const colors = new Map(source.color.tokens.map((t) => [t.name, t.value]));
  const resolve = (value: string): string => {
    const ref = referenceOf(value);
    if (ref === undefined) return value;
    const target = colors.get(ref);
    if (target === undefined) throw new Error(`tokens.json: unknown reference {${ref}}`);
    return resolve(target);
  };
  const scale = (list: Token[], prefix: string, map = resolve) =>
    Object.fromEntries(list.map((t) => [strip(t.name, prefix), map(t.value)]));
  const own = (group: ExtendGroup) => scale(extend[group].tokens, '', (v) => v);
  const styles = source.type.groups.flatMap((g) =>
    g.styles.map((s) => ({ ...s, family: s.family ?? g.family })),
  );

  const tokens = {
    color: merge(scale(source.color.tokens, ''), own('color'), 'color'),
    spacing: merge(scale(source.spacing.tokens, 'space-'), own('spacing'), 'spacing'),
    radius: merge(scale(source.radius.tokens, 'radius-'), own('radius'), 'radius'),
    shadow: merge(scale(source.shadow.tokens, 'shadow-'), own('shadow'), 'shadow'),
    dropShadow: own('dropShadow'),
    font: source.type.families,
    text: Object.fromEntries(
      styles.map(({ name, family, fontSize, lineHeight, fontWeight, letterSpacing }) => [
        name,
        { family, fontSize, lineHeight, fontWeight, letterSpacing },
      ]),
    ),
    fontSize: own('fontSize'),
    leading: own('leading'),
    tracking: own('tracking'),
    duration: merge(scale(source.duration.tokens, 'dur-'), own('duration'), 'duration'),
    ease: scale(source.easing.tokens, 'ease-'),
    breakpoint: own('breakpoint'),
    gridCols: own('gridCols'),
  };
  for (const key of Object.keys(tokens.fontSize)) {
    if (key in tokens.text)
      throw new Error(`extend.json: fontSize "${key}" clashes with a type style`);
  }

  const groups = [
    RESET.map((namespace) => `--${namespace}-*: initial;`),
    vars('color', { ...scale(source.color.tokens, '', alias), ...own('color') }),
    // Not a token: without a zero, p-0, inset-0 and min-w-0 compile to nothing.
    vars('spacing', { 0: '0px', ...tokens.spacing }),
    vars('radius', tokens.radius),
    vars('shadow', tokens.shadow),
    vars('drop-shadow', tokens.dropShadow),
    vars('font', tokens.font),
    styles.flatMap((s) => [
      `--text-${s.name}: ${s.fontSize};`,
      `--text-${s.name}--line-height: ${s.lineHeight};`,
      `--text-${s.name}--font-weight: ${s.fontWeight};`,
      ...(s.letterSpacing === undefined
        ? []
        : [`--text-${s.name}--letter-spacing: ${s.letterSpacing};`]),
    ]),
    vars('text', tokens.fontSize),
    vars('leading', tokens.leading),
    vars('tracking', tokens.tracking),
    vars('transition-duration', tokens.duration),
    vars('ease', tokens.ease),
    vars('breakpoint', tokens.breakpoint),
    vars('grid-template-columns', tokens.gridCols),
  ];
  const body = groups.map((lines) => lines.map((line) => `  ${line}`).join('\n')).join('\n\n');

  return {
    css: `/* ${HEADER} */\n@theme {\n${body}\n}\n`,
    ts: `// ${HEADER}\nexport const tokens = ${JSON.stringify(tokens, null, 2)} as const;\n`,
  };
}

if (import.meta.main) {
  const read = <T>(file: string) =>
    JSON.parse(readFileSync(new URL(`../tokens/${file}`, import.meta.url), 'utf8')) as T;
  const { css, ts } = buildTokens(
    read<TokenSource>('tokens.json'),
    read<ExtendSource>('extend.json'),
  );
  writeFileSync(new URL('../src/styles/theme.css', import.meta.url), css);
  writeFileSync(new URL('../src/tokens.ts', import.meta.url), ts);
}
