// Generates src/styles/theme.css and src/tokens.ts from tokens/tokens.json.
// After changing tokens.json, run `pnpm --filter @dailyx/ui tokens` and commit all three files.
import { readFileSync, writeFileSync } from 'node:fs';

interface Token {
  name: string;
  value: string;
}

interface TypeStyle {
  name: string;
  family?: string;
  fontSize: string;
  lineHeight: string;
  fontWeight: number;
  letterSpacing?: string;
}

export interface TokenSource {
  color: { tokens: Token[] };
  type: {
    families: Record<string, string>;
    groups: { family: string; styles: TypeStyle[] }[];
  };
  spacing: { tokens: Token[] };
  radius: { tokens: Token[] };
  shadow: { tokens: Token[] };
  duration: { tokens: Token[] };
  easing: { tokens: Token[] };
}

// Tailwind namespaces cleared so that only tokens compile. Breakpoints, containers and font
// weights keep Tailwind's defaults.
const RESET = [
  'color',
  'spacing',
  'radius',
  'shadow',
  'inset-shadow',
  'drop-shadow',
  'text-shadow',
  'font',
  'text',
  'ease',
];

const HEADER =
  'Generated by packages/ui/scripts/build-tokens.ts from packages/ui/tokens/tokens.json. Do not edit.';

const strip = (name: string, prefix: string) =>
  name.startsWith(prefix) ? name.slice(prefix.length) : name;

const referenceOf = (value: string) => /^\{(.+)\}$/.exec(value)?.[1];

// A reference stays an alias in CSS: {up} → var(--color-up).
const alias = (value: string) => {
  const ref = referenceOf(value);
  return ref === undefined ? value : `var(--color-${ref})`;
};

const vars = (namespace: string, record: Record<string, string>) =>
  Object.entries(record).map(([key, value]) => `--${namespace}-${key}: ${value};`);

export function buildTokens(source: TokenSource): { css: string; ts: string } {
  const colors = new Map(source.color.tokens.map((t) => [t.name, t.value]));
  const resolve = (value: string): string => {
    const ref = referenceOf(value);
    if (ref === undefined) return value;
    const target = colors.get(ref);
    if (target === undefined) throw new Error(`tokens.json: unknown reference {${ref}}`);
    return resolve(target);
  };
  const scale = (list: Token[], prefix: string, map = resolve) =>
    Object.fromEntries(list.map((t) => [strip(t.name, prefix), map(t.value)]));
  const styles = source.type.groups.flatMap((g) =>
    g.styles.map((s) => ({ ...s, family: s.family ?? g.family })),
  );

  const tokens = {
    color: scale(source.color.tokens, ''),
    spacing: scale(source.spacing.tokens, 'space-'),
    radius: scale(source.radius.tokens, 'radius-'),
    shadow: scale(source.shadow.tokens, 'shadow-'),
    font: source.type.families,
    text: Object.fromEntries(
      styles.map(({ name, family, fontSize, lineHeight, fontWeight, letterSpacing }) => [
        name,
        { family, fontSize, lineHeight, fontWeight, letterSpacing },
      ]),
    ),
    duration: scale(source.duration.tokens, 'dur-'),
    ease: scale(source.easing.tokens, 'ease-'),
  };

  const groups = [
    RESET.map((namespace) => `--${namespace}-*: initial;`),
    vars('color', scale(source.color.tokens, '', alias)),
    // Not a token: without a zero, p-0, inset-0 and min-w-0 compile to nothing.
    vars('spacing', { 0: '0px', ...tokens.spacing }),
    vars('radius', tokens.radius),
    vars('shadow', tokens.shadow),
    vars('font', tokens.font),
    styles.flatMap((s) => [
      `--text-${s.name}: ${s.fontSize};`,
      `--text-${s.name}--line-height: ${s.lineHeight};`,
      `--text-${s.name}--font-weight: ${s.fontWeight};`,
      ...(s.letterSpacing === undefined
        ? []
        : [`--text-${s.name}--letter-spacing: ${s.letterSpacing};`]),
    ]),
    vars('transition-duration', tokens.duration),
    vars('ease', tokens.ease),
  ];
  const body = groups.map((lines) => lines.map((line) => `  ${line}`).join('\n')).join('\n\n');

  return {
    css: `/* ${HEADER} */\n@theme {\n${body}\n}\n`,
    ts: `// ${HEADER}\nexport const tokens = ${JSON.stringify(tokens, null, 2)} as const;\n`,
  };
}

if (import.meta.main) {
  const source = JSON.parse(
    readFileSync(new URL('../tokens/tokens.json', import.meta.url), 'utf8'),
  ) as TokenSource;
  const { css, ts } = buildTokens(source);
  writeFileSync(new URL('../src/styles/theme.css', import.meta.url), css);
  writeFileSync(new URL('../src/tokens.ts', import.meta.url), ts);
}
