// Generated by packages/ui/scripts/build-tokens.ts from packages/ui/tokens/tokens.json. Do not edit.
export const tokens = {
  "color": {
    "bg-000": "#07090a",
    "bg-100": "#0e1211",
    "bg-200": "#151b19",
    "bg-300": "#1d2522",
    "line": "#1f2926",
    "line-strong": "#2c3833",
    "line-control": "#5d6b66",
    "ink": "#e9f0ec",
    "ink-muted": "#a0ada7",
    "ink-faint": "#838f8a",
    "up": "#3ddc84",
    "up-soft": "#0f2e1f",
    "on-up": "#04140b",
    "down": "#ff5c63",
    "down-soft": "#35141a",
    "warn": "#f5b841",
    "warn-soft": "#33270e",
    "info": "#5cc8e0",
    "info-soft": "#0f2a31",
    "sure-received": "#3ddc84",
    "sure-secured": "#2aa865",
    "sure-committed": "#22784b",
    "sure-pipeline": "#5d6b66",
    "series-1": "#3ddc84",
    "series-2": "#5cc8e0",
    "series-3": "#f5b841",
    "series-4": "#7aa2ff",
    "series-5": "#cfd8d3",
    "focus": "#8af5b8"
  },
  "spacing": {
    "1": "4px",
    "2": "8px",
    "3": "12px",
    "4": "16px",
    "5": "20px",
    "6": "24px",
    "8": "32px",
    "12": "48px"
  },
  "radius": {
    "sm": "6px",
    "md": "10px",
    "lg": "14px",
    "pill": "999px"
  },
  "shadow": {
    "card": "0 1px 0 rgba(255,255,255,0.03) inset, 0 8px 24px rgba(0,0,0,0.35)",
    "pop": "0 12px 32px rgba(0,0,0,0.55)",
    "glow-up": "0 0 0 1px rgba(61,220,132,0.45), 0 0 20px rgba(61,220,132,0.25)"
  },
  "font": {
    "sans": "Geist, \"Helvetica Neue\", Arial, sans-serif",
    "mono": "\"Geist Mono\", \"SFMono-Regular\", Menlo, Consolas, monospace"
  },
  "text": {
    "num-hero": {
      "family": "mono",
      "fontSize": "48px",
      "lineHeight": "52px",
      "fontWeight": 500,
      "letterSpacing": "-0.03em"
    },
    "num-lg": {
      "family": "mono",
      "fontSize": "28px",
      "lineHeight": "32px",
      "fontWeight": 500,
      "letterSpacing": "-0.02em"
    },
    "num-md": {
      "family": "mono",
      "fontSize": "16px",
      "lineHeight": "22px",
      "fontWeight": 500
    },
    "num-sm": {
      "family": "mono",
      "fontSize": "12px",
      "lineHeight": "16px",
      "fontWeight": 500
    },
    "display": {
      "family": "sans",
      "fontSize": "32px",
      "lineHeight": "36px",
      "fontWeight": 600,
      "letterSpacing": "-0.02em"
    },
    "title": {
      "family": "sans",
      "fontSize": "18px",
      "lineHeight": "24px",
      "fontWeight": 600,
      "letterSpacing": "-0.01em"
    },
    "body": {
      "family": "sans",
      "fontSize": "14px",
      "lineHeight": "20px",
      "fontWeight": 400
    },
    "body-strong": {
      "family": "sans",
      "fontSize": "14px",
      "lineHeight": "20px",
      "fontWeight": 600
    },
    "caption": {
      "family": "sans",
      "fontSize": "12px",
      "lineHeight": "16px",
      "fontWeight": 400
    },
    "eyebrow": {
      "family": "mono",
      "fontSize": "11px",
      "lineHeight": "16px",
      "fontWeight": 500,
      "letterSpacing": "0.08em"
    }
  },
  "duration": {
    "fast": "140ms",
    "base": "240ms",
    "chart": "900ms"
  },
  "ease": {
    "out": "cubic-bezier(0.22, 1, 0.36, 1)",
    "inout": "cubic-bezier(0.65, 0, 0.35, 1)"
  }
} as const;
