// Generated by packages/ui/scripts/build-tokens.ts from packages/ui/tokens/tokens.json and extend.json. Do not edit.
export const tokens = {
  "color": {
    "bg-000": "#07090a",
    "bg-100": "#0e1211",
    "bg-200": "#151b19",
    "bg-300": "#1d2522",
    "line": "#1f2926",
    "line-strong": "#2c3833",
    "line-control": "#5d6b66",
    "ink": "#e9f0ec",
    "ink-muted": "#a0ada7",
    "ink-faint": "#838f8a",
    "up": "#3ddc84",
    "up-soft": "#0f2e1f",
    "on-up": "#04140b",
    "down": "#ff5c63",
    "down-soft": "#35141a",
    "warn": "#f5b841",
    "warn-soft": "#33270e",
    "info": "#5cc8e0",
    "info-soft": "#0f2a31",
    "sure-received": "#3ddc84",
    "sure-secured": "#2aa865",
    "sure-committed": "#22784b",
    "sure-pipeline": "#5d6b66",
    "series-1": "#3ddc84",
    "series-2": "#5cc8e0",
    "series-3": "#f5b841",
    "series-4": "#7aa2ff",
    "series-5": "#cfd8d3",
    "focus": "#8af5b8",
    "up-hover": "#5ee79a",
    "on-warn": "#1d1405"
  },
  "spacing": {
    "1": "4px",
    "2": "8px",
    "3": "12px",
    "4": "16px",
    "5": "20px",
    "6": "24px",
    "8": "32px",
    "12": "48px",
    "1px": "1px",
    "2px": "2px",
    "3px": "3px",
    "6px": "6px",
    "7px": "7px",
    "9px": "9px",
    "10px": "10px",
    "14px": "14px",
    "18px": "18px",
    "22px": "22px",
    "26px": "26px",
    "28px": "28px",
    "30px": "30px",
    "34px": "34px",
    "36px": "36px",
    "38px": "38px",
    "40px": "40px",
    "44px": "44px",
    "52px": "52px",
    "56px": "56px",
    "58px": "58px",
    "64px": "64px",
    "112px": "112px",
    "120px": "120px",
    "156px": "156px",
    "340px": "340px",
    "360px": "360px",
    "364px": "364px",
    "1240px": "1240px"
  },
  "radius": {
    "sm": "6px",
    "md": "10px",
    "lg": "14px",
    "pill": "999px",
    "2px": "2px",
    "3px": "3px",
    "5px": "5px",
    "7px": "7px",
    "8px": "8px"
  },
  "shadow": {
    "card": "0 1px 0 rgba(255,255,255,0.03) inset, 0 8px 24px rgba(0,0,0,0.35)",
    "pop": "0 12px 32px rgba(0,0,0,0.55)",
    "glow-up": "0 0 0 1px rgba(61,220,132,0.45), 0 0 20px rgba(61,220,132,0.25)",
    "chip": "0 4px 12px rgba(0,0,0,0.4)",
    "lift": "0 14px 28px rgba(0,0,0,0.55)",
    "tab-sel": "inset 0 -2px 0 var(--color-up)"
  },
  "dropShadow": {
    "mastered": "0 0 12px rgba(61,220,132,0.28)",
    "lift": "0 14px 24px rgba(0,0,0,0.6)",
    "focus": "0 0 6px rgba(138,245,184,0.45)"
  },
  "font": {
    "sans": "Geist, \"Helvetica Neue\", Arial, sans-serif",
    "mono": "\"Geist Mono\", \"SFMono-Regular\", Menlo, Consolas, monospace"
  },
  "text": {
    "num-hero": {
      "family": "mono",
      "fontSize": "48px",
      "lineHeight": "52px",
      "fontWeight": 500,
      "letterSpacing": "-0.03em"
    },
    "num-lg": {
      "family": "mono",
      "fontSize": "28px",
      "lineHeight": "32px",
      "fontWeight": 500,
      "letterSpacing": "-0.02em"
    },
    "num-md": {
      "family": "mono",
      "fontSize": "16px",
      "lineHeight": "22px",
      "fontWeight": 500
    },
    "num-sm": {
      "family": "mono",
      "fontSize": "12px",
      "lineHeight": "16px",
      "fontWeight": 500
    },
    "display": {
      "family": "sans",
      "fontSize": "32px",
      "lineHeight": "36px",
      "fontWeight": 600,
      "letterSpacing": "-0.02em"
    },
    "title": {
      "family": "sans",
      "fontSize": "18px",
      "lineHeight": "24px",
      "fontWeight": 600,
      "letterSpacing": "-0.01em"
    },
    "body": {
      "family": "sans",
      "fontSize": "14px",
      "lineHeight": "20px",
      "fontWeight": 400
    },
    "body-strong": {
      "family": "sans",
      "fontSize": "14px",
      "lineHeight": "20px",
      "fontWeight": 600
    },
    "caption": {
      "family": "sans",
      "fontSize": "12px",
      "lineHeight": "16px",
      "fontWeight": 400
    },
    "eyebrow": {
      "family": "mono",
      "fontSize": "11px",
      "lineHeight": "16px",
      "fontWeight": 500,
      "letterSpacing": "0.08em"
    }
  },
  "fontSize": {
    "9px": "9px",
    "10px": "10px",
    "11px": "11px",
    "12px": "12px",
    "13px": "13px",
    "14px": "14px",
    "15px": "15px",
    "16px": "16px",
    "20px": "20px",
    "22px": "22px",
    "44px": "44px",
    "56px": "56px"
  },
  "leading": {
    "14px": "14px",
    "15px": "15px",
    "16px": "16px",
    "18px": "18px",
    "20px": "20px",
    "23px": "23px",
    "24px": "24px",
    "26px": "26px",
    "44px": "44px",
    "56px": "56px"
  },
  "tracking": {
    "seg": "0.04em",
    "scale": "0.06em",
    "rail": "0.14em",
    "hero": "-0.04em"
  },
  "duration": {
    "fast": "140ms",
    "base": "240ms",
    "chart": "900ms",
    "tip": "60ms",
    "glide": "300ms",
    "meter": "1100ms",
    "flow": "1.4s",
    "ping": "2.4s"
  },
  "ease": {
    "out": "cubic-bezier(0.22, 1, 0.36, 1)",
    "inout": "cubic-bezier(0.65, 0, 0.35, 1)"
  },
  "breakpoint": {
    "520": "32.5rem",
    "720": "45rem",
    "760": "47.5rem",
    "960": "60rem"
  },
  "gridCols": {
    "funnel": "112px 1fr 64px",
    "alloc": "10px 1fr auto 52px",
    "queue": "minmax(0, 1fr) 104px 64px minmax(150px, 220px)",
    "main-auto": "minmax(0, 1fr) auto",
    "milestones": "14px minmax(0, 1fr) auto 72px",
    "portfolio": "minmax(170px, 1.4fr) 72px 96px 64px minmax(150px, 1.3fr) 96px",
    "health": "repeat(auto-fill, minmax(200px, 1fr))",
    "pick": "repeat(auto-fill, minmax(260px, 1fr))",
    "hyp-form": "auto minmax(0, 1fr) minmax(0, 1fr)",
    "srcs": "repeat(auto-fit, minmax(220px, 1fr))",
    "wide": "minmax(0, 1.6fr) minmax(0, 1fr)"
  }
} as const;
